#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTUDQL.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyThuVien")]
	public partial class QuanLyThuVienDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAnh(Anh instance);
    partial void UpdateAnh(Anh instance);
    partial void DeleteAnh(Anh instance);
    partial void InsertCaiDat(CaiDat instance);
    partial void UpdateCaiDat(CaiDat instance);
    partial void DeleteCaiDat(CaiDat instance);
    partial void InsertChiTietMuonSach(ChiTietMuonSach instance);
    partial void UpdateChiTietMuonSach(ChiTietMuonSach instance);
    partial void DeleteChiTietMuonSach(ChiTietMuonSach instance);
    partial void InsertDocGia(DocGia instance);
    partial void UpdateDocGia(DocGia instance);
    partial void DeleteDocGia(DocGia instance);
    partial void InsertPhieuMuonSach(PhieuMuonSach instance);
    partial void UpdatePhieuMuonSach(PhieuMuonSach instance);
    partial void DeletePhieuMuonSach(PhieuMuonSach instance);
    partial void InsertSach(Sach instance);
    partial void UpdateSach(Sach instance);
    partial void DeleteSach(Sach instance);
    partial void InsertTempTable_MuonSach(TempTable_MuonSach instance);
    partial void UpdateTempTable_MuonSach(TempTable_MuonSach instance);
    partial void DeleteTempTable_MuonSach(TempTable_MuonSach instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertLapPhieu(LapPhieu instance);
    partial void UpdateLapPhieu(LapPhieu instance);
    partial void DeleteLapPhieu(LapPhieu instance);
    #endregion
		
		public QuanLyThuVienDataContext() : 
				base(global::LTUDQL.Properties.Settings.Default.QuanLyThuVienConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyThuVienDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyThuVienDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyThuVienDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyThuVienDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Anh> Anhs
		{
			get
			{
				return this.GetTable<Anh>();
			}
		}
		
		public System.Data.Linq.Table<CaiDat> CaiDats
		{
			get
			{
				return this.GetTable<CaiDat>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietMuonSach> ChiTietMuonSaches
		{
			get
			{
				return this.GetTable<ChiTietMuonSach>();
			}
		}
		
		public System.Data.Linq.Table<DocGia> DocGias
		{
			get
			{
				return this.GetTable<DocGia>();
			}
		}
		
		public System.Data.Linq.Table<PhieuMuonSach> PhieuMuonSaches
		{
			get
			{
				return this.GetTable<PhieuMuonSach>();
			}
		}
		
		public System.Data.Linq.Table<Sach> Saches
		{
			get
			{
				return this.GetTable<Sach>();
			}
		}
		
		public System.Data.Linq.Table<TempTable_MuonSach> TempTable_MuonSaches
		{
			get
			{
				return this.GetTable<TempTable_MuonSach>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<LapPhieu> LapPhieus
		{
			get
			{
				return this.GetTable<LapPhieu>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Anh")]
	public partial class Anh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdNguoiDung;
		
		private System.Data.Linq.Binary _Images;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdNguoiDungChanging(string value);
    partial void OnIdNguoiDungChanged();
    partial void OnImagesChanging(System.Data.Linq.Binary value);
    partial void OnImagesChanged();
    #endregion
		
		public Anh()
		{
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNguoiDung", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdNguoiDung
		{
			get
			{
				return this._IdNguoiDung;
			}
			set
			{
				if ((this._IdNguoiDung != value))
				{
					this.OnIdNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._IdNguoiDung = value;
					this.SendPropertyChanged("IdNguoiDung");
					this.OnIdNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Images", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Images
		{
			get
			{
				return this._Images;
			}
			set
			{
				if ((this._Images != value))
				{
					this.OnImagesChanging(value);
					this.SendPropertyChanging();
					this._Images = value;
					this.SendPropertyChanged("Images");
					this.OnImagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Anh_TaiKhoan", Storage="_TaiKhoan", ThisKey="IdNguoiDung", OtherKey="IdNguoiDung", IsUnique=true, IsForeignKey=false)]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.Anh = null;
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.Anh = this;
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CaiDat")]
	public partial class CaiDat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _i;
		
		private System.Nullable<int> _TuoiMuonSach;
		
		private System.Nullable<int> _HanSuDungThe;
		
		private System.Nullable<int> _NgayMuonToiDa;
		
		private System.Nullable<int> _SoLuongSachMuonToiDa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniChanging(int value);
    partial void OniChanged();
    partial void OnTuoiMuonSachChanging(System.Nullable<int> value);
    partial void OnTuoiMuonSachChanged();
    partial void OnHanSuDungTheChanging(System.Nullable<int> value);
    partial void OnHanSuDungTheChanged();
    partial void OnNgayMuonToiDaChanging(System.Nullable<int> value);
    partial void OnNgayMuonToiDaChanged();
    partial void OnSoLuongSachMuonToiDaChanging(System.Nullable<int> value);
    partial void OnSoLuongSachMuonToiDaChanged();
    #endregion
		
		public CaiDat()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_i", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int i
		{
			get
			{
				return this._i;
			}
			set
			{
				if ((this._i != value))
				{
					this.OniChanging(value);
					this.SendPropertyChanging();
					this._i = value;
					this.SendPropertyChanged("i");
					this.OniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuoiMuonSach", DbType="Int")]
		public System.Nullable<int> TuoiMuonSach
		{
			get
			{
				return this._TuoiMuonSach;
			}
			set
			{
				if ((this._TuoiMuonSach != value))
				{
					this.OnTuoiMuonSachChanging(value);
					this.SendPropertyChanging();
					this._TuoiMuonSach = value;
					this.SendPropertyChanged("TuoiMuonSach");
					this.OnTuoiMuonSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HanSuDungThe", DbType="Int")]
		public System.Nullable<int> HanSuDungThe
		{
			get
			{
				return this._HanSuDungThe;
			}
			set
			{
				if ((this._HanSuDungThe != value))
				{
					this.OnHanSuDungTheChanging(value);
					this.SendPropertyChanging();
					this._HanSuDungThe = value;
					this.SendPropertyChanged("HanSuDungThe");
					this.OnHanSuDungTheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMuonToiDa", DbType="Int")]
		public System.Nullable<int> NgayMuonToiDa
		{
			get
			{
				return this._NgayMuonToiDa;
			}
			set
			{
				if ((this._NgayMuonToiDa != value))
				{
					this.OnNgayMuonToiDaChanging(value);
					this.SendPropertyChanging();
					this._NgayMuonToiDa = value;
					this.SendPropertyChanged("NgayMuonToiDa");
					this.OnNgayMuonToiDaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongSachMuonToiDa", DbType="Int")]
		public System.Nullable<int> SoLuongSachMuonToiDa
		{
			get
			{
				return this._SoLuongSachMuonToiDa;
			}
			set
			{
				if ((this._SoLuongSachMuonToiDa != value))
				{
					this.OnSoLuongSachMuonToiDaChanging(value);
					this.SendPropertyChanging();
					this._SoLuongSachMuonToiDa = value;
					this.SendPropertyChanged("SoLuongSachMuonToiDa");
					this.OnSoLuongSachMuonToiDaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietMuonSach")]
	public partial class ChiTietMuonSach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPhieu;
		
		private string _MaMuon;
		
		private string _MaSach;
		
		private System.Nullable<int> _SoTT;
		
		private EntityRef<PhieuMuonSach> _PhieuMuonSach;
		
		private EntityRef<Sach> _Sach;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPhieuChanging(int value);
    partial void OnIdPhieuChanged();
    partial void OnMaMuonChanging(string value);
    partial void OnMaMuonChanged();
    partial void OnMaSachChanging(string value);
    partial void OnMaSachChanged();
    partial void OnSoTTChanging(System.Nullable<int> value);
    partial void OnSoTTChanged();
    #endregion
		
		public ChiTietMuonSach()
		{
			this._PhieuMuonSach = default(EntityRef<PhieuMuonSach>);
			this._Sach = default(EntityRef<Sach>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPhieu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPhieu
		{
			get
			{
				return this._IdPhieu;
			}
			set
			{
				if ((this._IdPhieu != value))
				{
					this.OnIdPhieuChanging(value);
					this.SendPropertyChanging();
					this._IdPhieu = value;
					this.SendPropertyChanged("IdPhieu");
					this.OnIdPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMuon", DbType="VarChar(10)")]
		public string MaMuon
		{
			get
			{
				return this._MaMuon;
			}
			set
			{
				if ((this._MaMuon != value))
				{
					if (this._PhieuMuonSach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMuonChanging(value);
					this.SendPropertyChanging();
					this._MaMuon = value;
					this.SendPropertyChanged("MaMuon");
					this.OnMaMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="VarChar(10)")]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					if (this._Sach.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaSachChanging(value);
					this.SendPropertyChanging();
					this._MaSach = value;
					this.SendPropertyChanged("MaSach");
					this.OnMaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTT", DbType="Int")]
		public System.Nullable<int> SoTT
		{
			get
			{
				return this._SoTT;
			}
			set
			{
				if ((this._SoTT != value))
				{
					this.OnSoTTChanging(value);
					this.SendPropertyChanging();
					this._SoTT = value;
					this.SendPropertyChanged("SoTT");
					this.OnSoTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuMuonSach_ChiTietMuonSach", Storage="_PhieuMuonSach", ThisKey="MaMuon", OtherKey="MaMuon", IsForeignKey=true)]
		public PhieuMuonSach PhieuMuonSach
		{
			get
			{
				return this._PhieuMuonSach.Entity;
			}
			set
			{
				PhieuMuonSach previousValue = this._PhieuMuonSach.Entity;
				if (((previousValue != value) 
							|| (this._PhieuMuonSach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuMuonSach.Entity = null;
						previousValue.ChiTietMuonSaches.Remove(this);
					}
					this._PhieuMuonSach.Entity = value;
					if ((value != null))
					{
						value.ChiTietMuonSaches.Add(this);
						this._MaMuon = value.MaMuon;
					}
					else
					{
						this._MaMuon = default(string);
					}
					this.SendPropertyChanged("PhieuMuonSach");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sach_ChiTietMuonSach", Storage="_Sach", ThisKey="MaSach", OtherKey="MaSach", IsForeignKey=true)]
		public Sach Sach
		{
			get
			{
				return this._Sach.Entity;
			}
			set
			{
				Sach previousValue = this._Sach.Entity;
				if (((previousValue != value) 
							|| (this._Sach.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Sach.Entity = null;
						previousValue.ChiTietMuonSaches.Remove(this);
					}
					this._Sach.Entity = value;
					if ((value != null))
					{
						value.ChiTietMuonSaches.Add(this);
						this._MaSach = value.MaSach;
					}
					else
					{
						this._MaSach = default(string);
					}
					this.SendPropertyChanged("Sach");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DocGia")]
	public partial class DocGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdDocGia;
		
		private string _TenDocGia;
		
		private string _NgaySinh;
		
		private string _CMND;
		
		private string _GioiTinh;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private string _Email;
		
		private string _LoaiDocGia;
		
		private string _NgayLap;
		
		private string _MaPhieu;
		
		private EntityRef<LapPhieu> _LapPhieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdDocGiaChanging(int value);
    partial void OnIdDocGiaChanged();
    partial void OnTenDocGiaChanging(string value);
    partial void OnTenDocGiaChanged();
    partial void OnNgaySinhChanging(string value);
    partial void OnNgaySinhChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnLoaiDocGiaChanging(string value);
    partial void OnLoaiDocGiaChanged();
    partial void OnNgayLapChanging(string value);
    partial void OnNgayLapChanged();
    partial void OnMaPhieuChanging(string value);
    partial void OnMaPhieuChanged();
    #endregion
		
		public DocGia()
		{
			this._LapPhieu = default(EntityRef<LapPhieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDocGia", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdDocGia
		{
			get
			{
				return this._IdDocGia;
			}
			set
			{
				if ((this._IdDocGia != value))
				{
					this.OnIdDocGiaChanging(value);
					this.SendPropertyChanging();
					this._IdDocGia = value;
					this.SendPropertyChanged("IdDocGia");
					this.OnIdDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDocGia", DbType="NVarChar(50)")]
		public string TenDocGia
		{
			get
			{
				return this._TenDocGia;
			}
			set
			{
				if ((this._TenDocGia != value))
				{
					this.OnTenDocGiaChanging(value);
					this.SendPropertyChanging();
					this._TenDocGia = value;
					this.SendPropertyChanged("TenDocGia");
					this.OnTenDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="NVarChar(50)")]
		public string NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="VarChar(13)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(3)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(11)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(80)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiDocGia", DbType="NVarChar(50)")]
		public string LoaiDocGia
		{
			get
			{
				return this._LoaiDocGia;
			}
			set
			{
				if ((this._LoaiDocGia != value))
				{
					this.OnLoaiDocGiaChanging(value);
					this.SendPropertyChanging();
					this._LoaiDocGia = value;
					this.SendPropertyChanged("LoaiDocGia");
					this.OnLoaiDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLap", DbType="VarChar(15)")]
		public string NgayLap
		{
			get
			{
				return this._NgayLap;
			}
			set
			{
				if ((this._NgayLap != value))
				{
					this.OnNgayLapChanging(value);
					this.SendPropertyChanging();
					this._NgayLap = value;
					this.SendPropertyChanged("NgayLap");
					this.OnNgayLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieu", DbType="VarChar(20)")]
		public string MaPhieu
		{
			get
			{
				return this._MaPhieu;
			}
			set
			{
				if ((this._MaPhieu != value))
				{
					if (this._LapPhieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhieuChanging(value);
					this.SendPropertyChanging();
					this._MaPhieu = value;
					this.SendPropertyChanged("MaPhieu");
					this.OnMaPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LapPhieu_DocGia", Storage="_LapPhieu", ThisKey="MaPhieu", OtherKey="MaPhieu", IsForeignKey=true)]
		public LapPhieu LapPhieu
		{
			get
			{
				return this._LapPhieu.Entity;
			}
			set
			{
				LapPhieu previousValue = this._LapPhieu.Entity;
				if (((previousValue != value) 
							|| (this._LapPhieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LapPhieu.Entity = null;
						previousValue.DocGias.Remove(this);
					}
					this._LapPhieu.Entity = value;
					if ((value != null))
					{
						value.DocGias.Add(this);
						this._MaPhieu = value.MaPhieu;
					}
					else
					{
						this._MaPhieu = default(string);
					}
					this.SendPropertyChanged("LapPhieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuMuonSach")]
	public partial class PhieuMuonSach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaMuon;
		
		private string _NgayMuon;
		
		private string _MaPhieu;
		
		private EntitySet<ChiTietMuonSach> _ChiTietMuonSaches;
		
		private EntityRef<LapPhieu> _LapPhieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMuonChanging(string value);
    partial void OnMaMuonChanged();
    partial void OnNgayMuonChanging(string value);
    partial void OnNgayMuonChanged();
    partial void OnMaPhieuChanging(string value);
    partial void OnMaPhieuChanged();
    #endregion
		
		public PhieuMuonSach()
		{
			this._ChiTietMuonSaches = new EntitySet<ChiTietMuonSach>(new Action<ChiTietMuonSach>(this.attach_ChiTietMuonSaches), new Action<ChiTietMuonSach>(this.detach_ChiTietMuonSaches));
			this._LapPhieu = default(EntityRef<LapPhieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMuon", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaMuon
		{
			get
			{
				return this._MaMuon;
			}
			set
			{
				if ((this._MaMuon != value))
				{
					this.OnMaMuonChanging(value);
					this.SendPropertyChanging();
					this._MaMuon = value;
					this.SendPropertyChanged("MaMuon");
					this.OnMaMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMuon", DbType="NVarChar(50)")]
		public string NgayMuon
		{
			get
			{
				return this._NgayMuon;
			}
			set
			{
				if ((this._NgayMuon != value))
				{
					this.OnNgayMuonChanging(value);
					this.SendPropertyChanging();
					this._NgayMuon = value;
					this.SendPropertyChanged("NgayMuon");
					this.OnNgayMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieu", DbType="VarChar(20)")]
		public string MaPhieu
		{
			get
			{
				return this._MaPhieu;
			}
			set
			{
				if ((this._MaPhieu != value))
				{
					if (this._LapPhieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhieuChanging(value);
					this.SendPropertyChanging();
					this._MaPhieu = value;
					this.SendPropertyChanged("MaPhieu");
					this.OnMaPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuMuonSach_ChiTietMuonSach", Storage="_ChiTietMuonSaches", ThisKey="MaMuon", OtherKey="MaMuon")]
		public EntitySet<ChiTietMuonSach> ChiTietMuonSaches
		{
			get
			{
				return this._ChiTietMuonSaches;
			}
			set
			{
				this._ChiTietMuonSaches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LapPhieu_PhieuMuonSach", Storage="_LapPhieu", ThisKey="MaPhieu", OtherKey="MaPhieu", IsForeignKey=true)]
		public LapPhieu LapPhieu
		{
			get
			{
				return this._LapPhieu.Entity;
			}
			set
			{
				LapPhieu previousValue = this._LapPhieu.Entity;
				if (((previousValue != value) 
							|| (this._LapPhieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LapPhieu.Entity = null;
						previousValue.PhieuMuonSaches.Remove(this);
					}
					this._LapPhieu.Entity = value;
					if ((value != null))
					{
						value.PhieuMuonSaches.Add(this);
						this._MaPhieu = value.MaPhieu;
					}
					else
					{
						this._MaPhieu = default(string);
					}
					this.SendPropertyChanged("LapPhieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietMuonSaches(ChiTietMuonSach entity)
		{
			this.SendPropertyChanging();
			entity.PhieuMuonSach = this;
		}
		
		private void detach_ChiTietMuonSaches(ChiTietMuonSach entity)
		{
			this.SendPropertyChanging();
			entity.PhieuMuonSach = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sach")]
	public partial class Sach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSach;
		
		private string _TenSach;
		
		private System.Nullable<int> _SoLuong;
		
		private string _NamXuatBan;
		
		private string _NhaXuatBan;
		
		private string _NgayVaoKho;
		
		private string _TheLoai;
		
		private string _TenTacGia;
		
		private EntitySet<ChiTietMuonSach> _ChiTietMuonSaches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSachChanging(string value);
    partial void OnMaSachChanged();
    partial void OnTenSachChanging(string value);
    partial void OnTenSachChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnNamXuatBanChanging(string value);
    partial void OnNamXuatBanChanged();
    partial void OnNhaXuatBanChanging(string value);
    partial void OnNhaXuatBanChanged();
    partial void OnNgayVaoKhoChanging(string value);
    partial void OnNgayVaoKhoChanged();
    partial void OnTheLoaiChanging(string value);
    partial void OnTheLoaiChanged();
    partial void OnTenTacGiaChanging(string value);
    partial void OnTenTacGiaChanged();
    #endregion
		
		public Sach()
		{
			this._ChiTietMuonSaches = new EntitySet<ChiTietMuonSach>(new Action<ChiTietMuonSach>(this.attach_ChiTietMuonSaches), new Action<ChiTietMuonSach>(this.detach_ChiTietMuonSaches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					this.OnMaSachChanging(value);
					this.SendPropertyChanging();
					this._MaSach = value;
					this.SendPropertyChanged("MaSach");
					this.OnMaSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSach", DbType="NVarChar(50)")]
		public string TenSach
		{
			get
			{
				return this._TenSach;
			}
			set
			{
				if ((this._TenSach != value))
				{
					this.OnTenSachChanging(value);
					this.SendPropertyChanging();
					this._TenSach = value;
					this.SendPropertyChanged("TenSach");
					this.OnTenSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamXuatBan", DbType="Char(4)")]
		public string NamXuatBan
		{
			get
			{
				return this._NamXuatBan;
			}
			set
			{
				if ((this._NamXuatBan != value))
				{
					this.OnNamXuatBanChanging(value);
					this.SendPropertyChanging();
					this._NamXuatBan = value;
					this.SendPropertyChanged("NamXuatBan");
					this.OnNamXuatBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhaXuatBan", DbType="NVarChar(100)")]
		public string NhaXuatBan
		{
			get
			{
				return this._NhaXuatBan;
			}
			set
			{
				if ((this._NhaXuatBan != value))
				{
					this.OnNhaXuatBanChanging(value);
					this.SendPropertyChanging();
					this._NhaXuatBan = value;
					this.SendPropertyChanged("NhaXuatBan");
					this.OnNhaXuatBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayVaoKho", DbType="NVarChar(50)")]
		public string NgayVaoKho
		{
			get
			{
				return this._NgayVaoKho;
			}
			set
			{
				if ((this._NgayVaoKho != value))
				{
					this.OnNgayVaoKhoChanging(value);
					this.SendPropertyChanging();
					this._NgayVaoKho = value;
					this.SendPropertyChanged("NgayVaoKho");
					this.OnNgayVaoKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheLoai", DbType="NVarChar(50)")]
		public string TheLoai
		{
			get
			{
				return this._TheLoai;
			}
			set
			{
				if ((this._TheLoai != value))
				{
					this.OnTheLoaiChanging(value);
					this.SendPropertyChanging();
					this._TheLoai = value;
					this.SendPropertyChanged("TheLoai");
					this.OnTheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTacGia", DbType="NVarChar(80)")]
		public string TenTacGia
		{
			get
			{
				return this._TenTacGia;
			}
			set
			{
				if ((this._TenTacGia != value))
				{
					this.OnTenTacGiaChanging(value);
					this.SendPropertyChanging();
					this._TenTacGia = value;
					this.SendPropertyChanged("TenTacGia");
					this.OnTenTacGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Sach_ChiTietMuonSach", Storage="_ChiTietMuonSaches", ThisKey="MaSach", OtherKey="MaSach")]
		public EntitySet<ChiTietMuonSach> ChiTietMuonSaches
		{
			get
			{
				return this._ChiTietMuonSaches;
			}
			set
			{
				this._ChiTietMuonSaches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietMuonSaches(ChiTietMuonSach entity)
		{
			this.SendPropertyChanging();
			entity.Sach = this;
		}
		
		private void detach_ChiTietMuonSaches(ChiTietMuonSach entity)
		{
			this.SendPropertyChanging();
			entity.Sach = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TempTable_MuonSach")]
	public partial class TempTable_MuonSach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STT;
		
		private string _Sach;
		
		private string _TheLoai;
		
		private string _TacGia;
		
		private string _MaSach;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnSachChanging(string value);
    partial void OnSachChanged();
    partial void OnTheLoaiChanging(string value);
    partial void OnTheLoaiChanged();
    partial void OnTacGiaChanging(string value);
    partial void OnTacGiaChanged();
    partial void OnMaSachChanging(string value);
    partial void OnMaSachChanged();
    #endregion
		
		public TempTable_MuonSach()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sach", DbType="NVarChar(50)")]
		public string Sach
		{
			get
			{
				return this._Sach;
			}
			set
			{
				if ((this._Sach != value))
				{
					this.OnSachChanging(value);
					this.SendPropertyChanging();
					this._Sach = value;
					this.SendPropertyChanged("Sach");
					this.OnSachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TheLoai", DbType="NVarChar(50)")]
		public string TheLoai
		{
			get
			{
				return this._TheLoai;
			}
			set
			{
				if ((this._TheLoai != value))
				{
					this.OnTheLoaiChanging(value);
					this.SendPropertyChanging();
					this._TheLoai = value;
					this.SendPropertyChanged("TheLoai");
					this.OnTheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TacGia", DbType="NVarChar(80)")]
		public string TacGia
		{
			get
			{
				return this._TacGia;
			}
			set
			{
				if ((this._TacGia != value))
				{
					this.OnTacGiaChanging(value);
					this.SendPropertyChanging();
					this._TacGia = value;
					this.SendPropertyChanged("TacGia");
					this.OnTacGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSach", DbType="VarChar(10)")]
		public string MaSach
		{
			get
			{
				return this._MaSach;
			}
			set
			{
				if ((this._MaSach != value))
				{
					this.OnMaSachChanging(value);
					this.SendPropertyChanging();
					this._MaSach = value;
					this.SendPropertyChanged("MaSach");
					this.OnMaSachChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IdNguoiDung;
		
		private string _PassND;
		
		private string _HoTen;
		
		private string _NgaySinh;
		
		private string _GioiTinh;
		
		private string _DiaChi;
		
		private string _SoDT;
		
		private EntitySet<LapPhieu> _LapPhieus;
		
		private EntityRef<Anh> _Anh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdNguoiDungChanging(string value);
    partial void OnIdNguoiDungChanged();
    partial void OnPassNDChanging(string value);
    partial void OnPassNDChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(string value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDTChanging(string value);
    partial void OnSoDTChanged();
    #endregion
		
		public TaiKhoan()
		{
			this._LapPhieus = new EntitySet<LapPhieu>(new Action<LapPhieu>(this.attach_LapPhieus), new Action<LapPhieu>(this.detach_LapPhieus));
			this._Anh = default(EntityRef<Anh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNguoiDung", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IdNguoiDung
		{
			get
			{
				return this._IdNguoiDung;
			}
			set
			{
				if ((this._IdNguoiDung != value))
				{
					if (this._Anh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._IdNguoiDung = value;
					this.SendPropertyChanged("IdNguoiDung");
					this.OnIdNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassND", DbType="Char(32) NOT NULL", CanBeNull=false)]
		public string PassND
		{
			get
			{
				return this._PassND;
			}
			set
			{
				if ((this._PassND != value))
				{
					this.OnPassNDChanging(value);
					this.SendPropertyChanging();
					this._PassND = value;
					this.SendPropertyChanged("PassND");
					this.OnPassNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(80) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="NVarChar(50)")]
		public string NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDT", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string SoDT
		{
			get
			{
				return this._SoDT;
			}
			set
			{
				if ((this._SoDT != value))
				{
					this.OnSoDTChanging(value);
					this.SendPropertyChanging();
					this._SoDT = value;
					this.SendPropertyChanged("SoDT");
					this.OnSoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_LapPhieu", Storage="_LapPhieus", ThisKey="IdNguoiDung", OtherKey="IdNguoiLap")]
		public EntitySet<LapPhieu> LapPhieus
		{
			get
			{
				return this._LapPhieus;
			}
			set
			{
				this._LapPhieus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Anh_TaiKhoan", Storage="_Anh", ThisKey="IdNguoiDung", OtherKey="IdNguoiDung", IsForeignKey=true)]
		public Anh Anh
		{
			get
			{
				return this._Anh.Entity;
			}
			set
			{
				Anh previousValue = this._Anh.Entity;
				if (((previousValue != value) 
							|| (this._Anh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Anh.Entity = null;
						previousValue.TaiKhoan = null;
					}
					this._Anh.Entity = value;
					if ((value != null))
					{
						value.TaiKhoan = this;
						this._IdNguoiDung = value.IdNguoiDung;
					}
					else
					{
						this._IdNguoiDung = default(string);
					}
					this.SendPropertyChanged("Anh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LapPhieus(LapPhieu entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = this;
		}
		
		private void detach_LapPhieus(LapPhieu entity)
		{
			this.SendPropertyChanging();
			entity.TaiKhoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LapPhieu")]
	public partial class LapPhieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhieu;
		
		private string _IdNguoiLap;
		
		private EntitySet<DocGia> _DocGias;
		
		private EntitySet<PhieuMuonSach> _PhieuMuonSaches;
		
		private EntityRef<TaiKhoan> _TaiKhoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuChanging(string value);
    partial void OnMaPhieuChanged();
    partial void OnIdNguoiLapChanging(string value);
    partial void OnIdNguoiLapChanged();
    #endregion
		
		public LapPhieu()
		{
			this._DocGias = new EntitySet<DocGia>(new Action<DocGia>(this.attach_DocGias), new Action<DocGia>(this.detach_DocGias));
			this._PhieuMuonSaches = new EntitySet<PhieuMuonSach>(new Action<PhieuMuonSach>(this.attach_PhieuMuonSaches), new Action<PhieuMuonSach>(this.detach_PhieuMuonSaches));
			this._TaiKhoan = default(EntityRef<TaiKhoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieu", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhieu
		{
			get
			{
				return this._MaPhieu;
			}
			set
			{
				if ((this._MaPhieu != value))
				{
					this.OnMaPhieuChanging(value);
					this.SendPropertyChanging();
					this._MaPhieu = value;
					this.SendPropertyChanged("MaPhieu");
					this.OnMaPhieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdNguoiLap", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string IdNguoiLap
		{
			get
			{
				return this._IdNguoiLap;
			}
			set
			{
				if ((this._IdNguoiLap != value))
				{
					if (this._TaiKhoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdNguoiLapChanging(value);
					this.SendPropertyChanging();
					this._IdNguoiLap = value;
					this.SendPropertyChanged("IdNguoiLap");
					this.OnIdNguoiLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LapPhieu_DocGia", Storage="_DocGias", ThisKey="MaPhieu", OtherKey="MaPhieu")]
		public EntitySet<DocGia> DocGias
		{
			get
			{
				return this._DocGias;
			}
			set
			{
				this._DocGias.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LapPhieu_PhieuMuonSach", Storage="_PhieuMuonSaches", ThisKey="MaPhieu", OtherKey="MaPhieu")]
		public EntitySet<PhieuMuonSach> PhieuMuonSaches
		{
			get
			{
				return this._PhieuMuonSaches;
			}
			set
			{
				this._PhieuMuonSaches.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TaiKhoan_LapPhieu", Storage="_TaiKhoan", ThisKey="IdNguoiLap", OtherKey="IdNguoiDung", IsForeignKey=true)]
		public TaiKhoan TaiKhoan
		{
			get
			{
				return this._TaiKhoan.Entity;
			}
			set
			{
				TaiKhoan previousValue = this._TaiKhoan.Entity;
				if (((previousValue != value) 
							|| (this._TaiKhoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TaiKhoan.Entity = null;
						previousValue.LapPhieus.Remove(this);
					}
					this._TaiKhoan.Entity = value;
					if ((value != null))
					{
						value.LapPhieus.Add(this);
						this._IdNguoiLap = value.IdNguoiDung;
					}
					else
					{
						this._IdNguoiLap = default(string);
					}
					this.SendPropertyChanged("TaiKhoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DocGias(DocGia entity)
		{
			this.SendPropertyChanging();
			entity.LapPhieu = this;
		}
		
		private void detach_DocGias(DocGia entity)
		{
			this.SendPropertyChanging();
			entity.LapPhieu = null;
		}
		
		private void attach_PhieuMuonSaches(PhieuMuonSach entity)
		{
			this.SendPropertyChanging();
			entity.LapPhieu = this;
		}
		
		private void detach_PhieuMuonSaches(PhieuMuonSach entity)
		{
			this.SendPropertyChanging();
			entity.LapPhieu = null;
		}
	}
}
#pragma warning restore 1591
